version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: vue-todo-app
    ports:
      - "8081:80"
    volumes:
      - ./app/dist:/app/dist
  
  nginx:
    image: nginx:alpine
    container_name: nginx-todo-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app